### ISSUE TITLE
pc_access.c:318:46: error: AggState v1.0.1

### ISSUE THREAD

**Issue by animecomico** [pgpointcloud/pointcloud#174]
Hi, 

When build with CMake tag version 1.0.1 i have this error:

pointcloud/pgsql/pc_access.c:318:46: error: ‘AggState {aka struct AggState}’ has no member named ‘aggcontext’
   aggcontext = ((AggState *) fcinfo->context)->aggcontext;

Help me

**Comment by elemoine** [comment]
I guess the issue is related to the Postgres version you are using. What Postgres version are you using? Can you try with `master` rather than `1.0.1`?

**Comment by animecomico** [comment]
Hi, 
I use postgresql 9.5 and see the problem, in /usr/include/postgresql/9.5/server/nodes/execnodes.h
AggState struct have ExprContext **aggcontexts; not **aggcontext. 

So, i change in pc_acces.c aggcontext by aggcontexts

Build succesfully.

**Comment by elemoine** [comment]
Can you use the `master` branch of pointcloud? It should build against Postgres 9.5 without modifications.

**Comment by animecomico** [comment]
No is use branch v1.0.1.

Ok i use master branch

Thanks
