### ISSUE TITLE
Release notes should note no longer works with PostgreSQL 9.6

### ISSUE THREAD

**Issue by robe2** [pgpointcloud/pointcloud#328]
Since 9.6 is EOL, there is no reason to support it anymore, however, I think compiling against 9.6 worked fine in 1.2.1 (not sure about 1.2.2 though).  It definitely fails on 1.2.3 with this error.  All I ask is to update the release notes and readme that PostgreSQL 10 or above is required now.

```
-IE:/jenkins/postgresql/rel/pg9.6w64gcc81/include/server/port/win32 -DWIN32_STACK_RLIMIT=4194304  -c -o pc_pgsql.o pc_pgsql.c
pc_pgsql.c:32:10: fatal error: utils/regproc.h: No such file or directory
 #include "utils/regproc.h"
          ^~~~~~~~~~~~~~~~~
```

**Comment by pblottiere** [comment]
Thanks for pointing that out @robe2. I removed PG 9.6 from the CI some months ago but I didn't update the NEWS doc accordingly. Sorry :/.
